Update README.md
Psywerx/psywerx pull request #14
Opened 2019-03-16 04:19 UTC by Smotko

Testing some cool new features coming! 🌟

```
1 + 1 = 2
```

# Still a lot to do

* Comments
* Review requested/review dismissed messages
* Commits pushed?
* etc.

But slowly and surely getting there.

2019-03-16 04:21 UTC, smotko-mock requested changes
This could really use some more changes. Don't you think?

2019-03-16 04:21 UTC, smotko-mock approved these changes
On second thought... It's probably fine.

2019-03-16 04:22 UTC, smotko-mock reviewed
Or maybe I need to add a comment.

2019-03-17 01:33 UTC, smotko-mock approved these changes
Kk

2019-03-18 15:01 UTC, zidarsk8 commented
what

2019-03-18 15:02 UTC, zidarsk8 submitted a review, later dismissed
I think the "cool" should be removed /joke

2019-03-18 15:37 UTC, smotko-mock requested changes
I agree, not cool. Not even working apparently.

2019-03-18 15:46 UTC, zidarsk8 commented on README.md
> +Testing some cool new features. Ignore me :)
You shall never be ignored!

2019-03-18 15:46 UTC, zidarsk8 requested changes
The last part does not compute. Please remove

2019-05-28 06:56 UTC, closed without merging